volumes:
  pgdata:
  redis:
  static:
  media:


services:
  django:
    image: ghcr.io/j3rrryy/school_464:test
    expose:
      - 8000
    env_file:
      - ./test/.env
    volumes:
      - static:/app/static
      - media:/app/media
    depends_on:
      - postgres
      - redis
    command: bash -c "
      python manage.py collectstatic --no-input &&
      python manage.py makemigrations --merge &&
      python manage.py migrate &&
      coverage run manage.py test &&
      coverage xml -o ./coverage.xml"
    container_name: django_test

  postgres:
    image: postgres:alpine
    restart: always
    env_file:
      - ./test/.env
    volumes:
      - pgdata:/var/lib/postgresql/data/
    container_name: postgres_test

  redis:
    image: redis:alpine
    expose:
      - 6379
    env_file:
      - ./test/.env
    volumes:
      - redis:/data
    container_name: redis_test
