version: "3.9"

volumes:
  pgdata:
  static:
  media:


services:
  django:
    build:
      context: .
    ports:
      - 8000:8000
    env_file:
      - docker/env/.env.dev
    environment:
      - DEBUG=0
    volumes:
      - ./:/app
      - static:/app/static
      - media:/app/media
    depends_on:
      - postgres
      - redis
    command: bash -c "
      python manage.py collectstatic --no-input &&
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py test main"
    container_name: school_464_django_test

  nginx:
    image: nginx:stable-alpine
    restart: always
    working_dir: /app
    ports:
      - 80:80
    volumes:
      - static:/app/static
      - media:/app/media
      - ./docker/nginx/dev/:/etc/nginx/conf.d:ro
    links:
      - django
    depends_on:
      - django
    container_name: school_464_nginx_test

  postgres:
    image: postgres:alpine
    restart: always
    env_file:
      - docker/env/.env.dev
    volumes:
      - pgdata:/var/lib/postgresql/data/
    container_name: school_464_postgres_test

  redis:
    image: redis:alpine
    restart: always
    command:
      - redis-server
    ports:
      - 6379:6379
    env_file:
      - docker/env/.env.dev
    container_name: school_464_redis_test