version: '3.9'

volumes:
  pgdata_test:
  redis_test:
  static_test:
  media_test:


services:
  django:
    build:
      context: .
    expose:
      - 8000
    env_file:
      - docker/env/.env.dev
    environment:
      - DEBUG=0
    volumes:
      - static_test:/app/static
      - media_test:/app/media
    depends_on:
      - postgres
      - redis
    command: bash -c "
      python manage.py collectstatic --no-input &&
      python manage.py makemigrations &&
      python manage.py migrate &&
      coverage run manage.py test &&
      coverage xml"
    container_name: school_464_django_test

  postgres:
    image: postgres:alpine
    restart: always
    env_file:
      - docker/env/.env.dev
    volumes:
      - pgdata_test:/var/lib/postgresql/data/
    container_name: school_464_postgres_test

  redis:
    image: redis:alpine
    restart: always
    command:
      - redis-server
    expose:
      - 6379
    env_file:
      - docker/env/.env.dev
    volumes:
      - redis_test:/data
    container_name: school_464_redis_test