volumes:
  pgdata:
  static:
  media:

networks:
  nginx:
  backend:


services:
  nginx:
    image: nginx:1.28.0-alpine
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - static:/app/static
      - media:/app/media
      - ./dev/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - nginx
    depends_on:
      - django
    container_name: nginx_dev

  django:
    build:
      context: .
    restart: unless-stopped
    expose:
      - 8000
    env_file:
      - ./dev/.env
    volumes:
      - ./:/app
      - static:/app/static
      - media:/app/media
    networks:
      - nginx
      - backend
    depends_on:
      - postgres
    command: sh -c "
      chmod -R 755 /app/static/ &&
      chmod -R 755 /app/media/ &&
      uv run python manage.py runserver 0.0.0.0:8000"
    container_name: django_dev

  postgres:
    image: postgres:16.10-alpine
    restart: unless-stopped
    env_file:
      - ./dev/.env
    volumes:
      - pgdata:/var/lib/postgresql/data/
    networks:
      - backend
    container_name: postgres_dev
