volumes:
  pgdata:
  static:
  media:


services:
  django:
    image: django:test
    env_file:
      - ./test/.env
    volumes:
      - static:/app/static
      - media:/app/media
    depends_on:
      postgres:
        condition: service_healthy
    command: sh -c "
      uv sync --group test &&
      uv run --group test coverage run manage.py test &&
      uv run --group test coverage xml -o ./coverage.xml"
    container_name: django_test

  postgres:
    image: postgres:17.5-alpine
    env_file:
      - ./test/.env
    volumes:
      - pgdata:/var/lib/postgresql/data/
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    container_name: postgres_test
