volumes:
  pgdata:
  redis:
  static:
  media:


services:
  django:
    image: ghcr.io/j3rrryy/school_464:latest
    env_file:
      - ./test/.env
    volumes:
      - static:/app/static
      - media:/app/media
    depends_on:
      - postgres
      - redis
    command: sh -c "
      uv sync --group test &&
      uv run --group test coverage run manage.py test &&
      uv run --group test coverage xml -o ./coverage.xml"
    container_name: django_test

  postgres:
    image: postgres:17.5-alpine
    restart: unless-stopped
    env_file:
      - ./test/.env
    volumes:
      - pgdata:/var/lib/postgresql/data/
    container_name: postgres_test

  redis:
    image: redis:8.2-alpine
    restart: unless-stopped
    volumes:
      - redis:/data/
    container_name: redis_test
