volumes:
  pgdata_test:
  redis_test:
  static_test:
  media_test:


services:
  django:
    build:
      context: .
    expose:
      - 8000
    env_file:
      - ./docker/env/.env.dev
    environment:
      - DEBUG=0
    volumes:
      - ./:/app
      - static_test:/app/static
      - media_test:/app/media
    depends_on:
      - postgres
      - redis
    command: bash -c "
      python manage.py collectstatic --no-input &&
      python manage.py makemigrations --merge &&
      python manage.py migrate &&
      pip install ruff &&
      ruff check &&
      coverage run manage.py test &&
      coverage xml -o ./coverage.xml"
    container_name: django_test

  postgres:
    image: postgres:alpine
    restart: always
    env_file:
      - ./docker/env/.env.dev
    volumes:
      - pgdata_test:/var/lib/postgresql/data/
    container_name: postgres_test

  redis:
    image: redis:alpine
    restart: always
    command:
      - redis-server
    expose:
      - 6379
    env_file:
      - ./docker/env/.env.dev
    volumes:
      - redis_test:/data
    container_name: redis_test