volumes:
  pgdata:
  redis:
  static:
  media:

networks:
  nginx_network:
  main_network:


services:
  nginx:
    image: nginx:stable-alpine
    restart: always
    working_dir: /app
    ports:
      - 80:80
    volumes:
      - static:/app/static
      - media:/app/media
      - ./dev/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - nginx_network
    depends_on:
      - django
    container_name: nginx_dev

  django:
    build:
      context: .
    restart: always
    expose:
      - 8000
    env_file:
      - ./dev/.env
    volumes:
      - ./:/app
      - static:/app/static
      - media:/app/media
    networks:
      - nginx_network
      - main_network
    depends_on:
      - postgres
      - redis
    command: bash -c "
      python manage.py collectstatic --no-input &&
      python manage.py makemigrations --merge &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    container_name: django_dev

  postgres:
    image: postgres:alpine
    restart: always
    env_file:
      - ./dev/.env
    volumes:
      - pgdata:/var/lib/postgresql/data/
    networks:
      - main_network
    container_name: postgres_dev

  redis:
    image: redis:alpine
    restart: always
    expose:
      - 6379
    env_file:
      - ./dev/.env
    volumes:
      - redis:/data
    networks:
      - main_network
    container_name: redis_dev
