# Generated by Django 4.2.1 on 2023-12-13 17:28

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Содержимое страницы'),
        ),
    ]
