# Generated by Django 5.2.6 on 2025-09-23 20:34

from django.db import migrations, models


def migrate_page_data(apps, schema_editor):
    Page = apps.get_model("main", "Page")

    for page in Page.objects.all():
        parent_name = getattr(page, "parent_page", None)
        if parent_name and parent_name != "---------":
            try:
                parent_obj = Page.objects.get(name=parent_name)
                page.parent = parent_obj
                page.save(update_fields=["parent"])
            except Page.DoesNotExist:
                continue


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_alter_banner_banner_alter_news_photo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="page",
            old_name="menu_info",
            new_name="name",
        ),
        migrations.AlterField(
            model_name="page",
            name="name",
            field=models.CharField(max_length=255, unique=True, verbose_name="Имя"),
        ),
        migrations.AddField(
            model_name="page",
            name="parent",
            field=models.ForeignKey(
                "self",
                null=True,
                blank=True,
                on_delete=models.SET_NULL,
                related_name="children",
                verbose_name="Родительский пункт меню",
            ),
        ),
        migrations.RunPython(migrate_page_data),
        migrations.RemoveField(
            model_name="page",
            name="parent_page",
        ),
    ]
