# Generated by Django 5.0.14 on 2025-09-24 12:37

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_auto_20250923_2334"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name="page",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AlterField(
            model_name="page",
            name="content",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Содержимое"),
        ),
        migrations.AlterField(
            model_name="page",
            name="in_menu",
            field=models.BooleanField(default=True, verbose_name="Включена в меню"),
        ),
        migrations.AlterField(
            model_name="page",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="main.page",
                verbose_name="Родительский пункт меню",
            ),
        ),
        migrations.AddIndex(
            model_name="news",
            index=models.Index(
                condition=models.Q(("is_published", True)),
                fields=["is_pinned", "id"],
                name="news_pub_pin_id_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="news",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="news_search_vector_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="page",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="page_search_vector_idx"
            ),
        ),
    ]
