# Generated by Django 5.0.14 on 2025-09-24 12:51

from django.contrib.postgres.search import SearchVector
from django.db import migrations


def populate_search_vector(apps, schema_editor):
    News = apps.get_model("main", "News")
    Page = apps.get_model("main", "Page")

    News.objects.update(
        search_vector=SearchVector("headline", weight="A")
        + SearchVector("text", weight="B")
    )
    Page.objects.update(
        search_vector=SearchVector("name", weight="A")
        + SearchVector("content", weight="B")
    )


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_news_search_vector_page_search_vector_and_more"),
    ]

    operations = [
        migrations.RunPython(populate_search_vector),
    ]
