volumes:
  pgdata:
  redis:
  static:
  media:
  certbot_conf:
  certbot_www:

networks:
  nginx_network:
  main_network:


services:
  nginx:
    image: nginx:stable-alpine
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - static:/app/static
      - media:/app/media
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - certbot_conf:/etc/letsencrypt:ro
      - certbot_www:/var/www/certbot:ro
    networks:
      - nginx_network
    depends_on:
      - django
    container_name: nginx_prod

  django:
    image: ghcr.io/j3rrryy/school_464:latest
    pull_policy: always
    restart: always
    expose:
      - 8000
    env_file:
      - ./.env
    volumes:
      - static:/app/static
      - media:/app/media
    networks:
      - nginx_network
      - main_network
    depends_on:
      - postgres
      - redis
    command: sh -c "
      chmod -R 755 /app/static/ &&
      chmod -R 755 /app/media/ &&
      uv run gunicorn --workers=2 --max-requests=500 backend.wsgi -b 0.0.0.0:8000"
    container_name: django_prod

  postgres:
    image: postgres:alpine
    restart: always
    env_file:
      - ./.env
    volumes:
      - pgdata:/var/lib/postgresql/data/
    networks:
      - main_network
    container_name: postgres_prod

  redis:
    image: redis:alpine
    restart: always
    expose:
      - 6379
    volumes:
      - redis:/data
    networks:
      - main_network
    container_name: redis_prod
