volumes:
  pgdata:
  static:
  media:
  certbot_conf:
  certbot_www:

networks:
  nginx:
  backend:


services:
  nginx:
    image: nginx:1.28.0-alpine
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - static:/app/static
      - media:/app/media
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - certbot_conf:/etc/letsencrypt:ro
      - certbot_www:/var/www/certbot:ro
    networks:
      - nginx
    depends_on:
      - django
    container_name: nginx_prod

  django:
    image: ghcr.io/j3rrryy/school_464:latest
    pull_policy: always
    restart: unless-stopped
    expose:
      - 8000
    env_file:
      - ./.env
    volumes:
      - static:/app/static
      - media:/app/media
    networks:
      - nginx
      - backend
    depends_on:
      - postgres
    command: sh -c "
      chmod -R 755 /app/static/ &&
      chmod -R 755 /app/media/ &&
      uv run gunicorn --workers=2 --max-requests=500 backend.wsgi -b 0.0.0.0:8000"
    container_name: django_prod

  postgres:
    image: postgres:17.5-alpine
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - pgdata:/var/lib/postgresql/data/
    networks:
      - backend
    container_name: postgres_prod
