volumes:
  certbot_conf:
  certbot_www:


services:
  nginx:
    image: nginx:stable-alpine
    restart: always
    working_dir: /app
    ports:
      - 80:80
    volumes:
      - ./nginx.cert.conf:/etc/nginx/conf.d/default.conf:ro
      - certbot_conf:/etc/letsencrypt:ro
      - certbot_www:/var/www/certbot:ro
    container_name: nginx_cert

  certbot:
    image: certbot/certbot
    volumes:
      - certbot_conf:/etc/letsencrypt:rw
      - certbot_www:/var/www/certbot:rw
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www/certbot/ --email <your_email> --agree-tos --no-eff-email -d <domain (example.com)> -d <domain (www.example.com)>
    container_name: certbot_cert
