name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Copy .env.example
        run: cp examples/docker/env/.env.dev.example docker/env/.env.dev

      - name: Build and run Docker container
        run: |
          docker compose -f docker-compose.dev.yml up --build -d
          sleep 10
          docker compose exec school_464_django_dev sh -c "python manage.py test main"
